version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    docker:
      - image: cimg/node:current-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
    steps:
      - browser-tools/install-chrome
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: cd dist && npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
