version: 2.1
orbs:
  node: circleci/node@4
  browser-tools: circleci/browser-tools@1
  codecov: codecov/codecov@1
jobs:
  test:
    docker:
      - image: cimg/node:current-browsers
        environment:
          CHROME_BIN: '/usr/local/bin/google-chrome'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: lint
          command: npm run lint
      - codecov/upload
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: cd dist && npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
