version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: ghpages
          command: npm run ghpages
  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
